spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8001
spring:
  profiles: dev
  application:
   name: microservicecloud-config-dept
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource           # 当前数据源操作类型
   driver-class-name: org.gjt.mm.mysql.Driver             # mysql驱动包
   url: jdbc:mysql://localhost:3306/clouddb01             # 数据库名称
   username: root
   password: root
   dbcp2:
     min-idle: 5                                          # 数据库连接池的最小维持连接数
     initial-size: 5                                      # 初始化连接数
     max-total: 5                                         # 最大连接数
     max-wait-millis: 200                                 # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
  type-aliases-package: com.xudan.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    register-with-eureka: true  #是否向注册中心注册自己
    fetch-registry: true #是否获取注册表
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:  
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true #访问路径可以显示ip地址
    
info: 
  app.name: xudan-microservicecloud
  company.name: www.xdzyl.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
  port: 8001
spring:
  profiles: test
  application:
   name: microservicecloud-config-dept
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource           # 当前数据源操作类型
   driver-class-name: org.gjt.mm.mysql.Driver             # mysql驱动包
   url: jdbc:mysql://localhost:3306/clouddb02             # 数据库名称
   username: root
   password: root
   dbcp2:
     min-idle: 5                                          # 数据库连接池的最小维持连接数
     initial-size: 5                                      # 初始化连接数
     max-total: 5                                         # 最大连接数
     max-wait-millis: 200                                 # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
  type-aliases-package: com.xudan.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    register-with-eureka: true  #是否向注册中心注册自己
    fetch-registry: true #是否获取注册表
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:  
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true #访问路径可以显示ip地址
    
info: 
  app.name: xudan-microservicecloud
  company.name: www.xdzyl.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$